/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    AddCard: typeof import('./src/components/AddCard.vue')['default']
    CheckCard: typeof import('./src/components/CheckCard.vue')['default']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElContainer: typeof import('element-plus/es')['ElContainer']
    ElContaner: typeof import('element-plus/es')['ElContaner']
    ElDialog: typeof import('element-plus/es')['ElDialog']
    ElFooter: typeof import('element-plus/es')['ElFooter']
    ElHeader: typeof import('element-plus/es')['ElHeader']
    ElMain: typeof import('element-plus/es')['ElMain']
    QRCode: typeof import('./src/components/QRCode.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SeachBar: typeof import('./src/components/SeachBar.vue')['default']
    SignInItems: typeof import('./src/components/SignInItems.vue')['default']
  }
}
